const ScreenConst = {
  ANIMELISTAIRING: 'ANIMELISTAIRING',
  ANIMELISTCOMPLETE: 'ANIMELISTCOMPLETE',
  ANIMELISTUPCOMING: 'ANIMELISTUPCOMING',
  ANIMELISTDETAIL: 'ANIMELISTDETAIL',
  FAVOURITEANIMELIST: 'FAVOURITEANIMELIST',
  ANIMEBOTTOMTAB: 'ANIMEBOTTOMTAB',
};

export default ScreenConst;
